services:
  postgres:
    image: 'postgres:15.3'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - 5432:5432

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379

