spring:
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    com:
      geekbrains:
        shop: DEBUG

