-- create table orders
-- (
--     id bigserial primary key,
--     uuid uuid not null,
--     price bigint,
--     created_at timestamp default current_timestamp,
--     updated_at timestamp default current_timestamp
-- );
--
-- create table orders_products
-- (
--     id bigserial primary key,
--     order_id bigint references orders(id),
--     product_id bigint references products(id)
--
-- );